#!/bin/bash

ABSPATH=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$ABSPATH")
cd $SCRIPTPATH

#WEEK=$(date +"%u")
#cat /var/log/mail.log |grep UGFzc3dvcmQ6 |cut -d [ -f 3| cut -d ] -f 1|uniq > $WEEK
iptables -F

rm -f saslerrorlog.2
mv saslerrorlog.1 saslerrorlog.2
mv saslerrorlog saslerrorlog.1

cat /var/log/mail.log* |grep UGFzc3dvcmQ6 |cut -d [ -f 3| cut -d ] -f 1 |sort | uniq -c | sort -nr -t 1 > saslerrorlog

BANIP=$(cat saslerrorlog*|awk '$1 >= 50 {print $2 }')
#echo "$BANIP"

for i in $BANIP
do
         iptables -A INPUT -s $i/32 -j DROP

done

